config/routes.rb
Rails.application.routes.draw do
  get 'aspires/new'
  get 'aspires/edit'
  get 'educational_backgrounds/new'
  get 'educational_backgrounds/edit'
  root 'home#top'
  get 'home/about'
  devise_for :students, controllers:{
    sessions: "students/sessions",
    passwords: "students/passwords",
    registrations: "students/registrations"
  }
  resources :students, only:[:index, :show, :edit, :update, :destroy] do
    resources :educational_backgrounds, only:[:new, :create, :edit, :update]
    resources :aspires, only:[:new, :create, :edit, :update]
  end
  resources :follows, only:[:create, :destroy]
  resources :requests do
    get "videos/request_new"
    post "videos/request_create"
  end
  resources :videos do
    resources :comments, only:[:create, :destroy]
    resources :evaluations, only:[:create, :update, :destroy]
  end
  resources :communities do
    member do
      post "add"
      delete "out"
    end
    resources :tweets, only:[:new, :create, :destroy]
  end
  resources :tweets, only:[:show] do
    resources :reply_tweets, only:[:new, :create, :destroy]
    resources :tweet_evaluations, only:[:create, :destroy]
  end
  resources :comments, only:[:show] do
    resources :reply_comments, only:[:new, :create, :destroy]
    resources :comment_evaluations, only:[:create, :destroy]
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/student.rb
class Student < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  enum grade:{
    p_1: 1, p_2: 2, p_3: 3, p_4: 4, p_5: 5, p_6: 6,
    m_1: 7, m_2: 8, m_3: 9, h_1: 10, h_2: 11, h_3: 12, other: 13
  }

  has_one :educational_background, dependent: :destroy
  has_one :watch_point, dependent: :destroy
  has_one :aspire, dependent: :destroy
  has_many :requests, dependent: :destroy
  has_many :videos, dependent: :nullify
  has_many :comments, dependent: :nullify
  has_many :evaluations, dependent: :nullify
  has_many :tweets, dependent: :nullify
  has_many :reply_tweets, dependent: :nullify
  has_many :tweet_evaluations, dependent: :nullify
  has_many :reply_comments, dependent: :nullify
  has_many :comment_evaluations, dependent: :nullify

  # watchリレーション
  has_many :watches, dependent: :nullify
  has_many :watched_videos, through: :watches, source: "video"

  # followリレーション
  has_many :follows, dependent: :destroy
  has_many :follow_students, through: :follows, source: "follow"
  has_many :followed, class_name: "Follow", foreign_key: "follow_id"
  has_many :followed_students, through: :followed, source: :student

  # communityリレーション
  has_many :student_communities, dependent: :destroy
  has_many :communities, through: :student_communities, source: "community"

  # adminになったコミュニティ
  has_many :communities, dependent: :nullify, foreign_key: "admin_id"

  mount_uploader :image, ImageUploader

  validates :name, presence: true
  validates :grade, presence: true

  def thumnail_image
    if self.image.blank?
      "no_image.png"
    else
      self.image.thumnail.to_s
    end
  end

  def info_image
    if self.image.blank?
      "no_image.png"
    else
      self.image.info.to_s
    end
  end

  def watched?(video)
    self.watches.find_by(video_id: video.id)
  end

  # 引数で渡された生徒をフォローする
  def follow(student)
    unless self == student
      self.follows.find_or_create_by(follow_id: student.id)
    end
  end

  # 引数で渡された生徒のフォローを解除する
  def unfollow(student)
    follow = self.follows.find_by(follow_id: student.id)
    follow.destroy if follow
  end

  # 引数で渡された生徒をフォローしているかを判別する
  def follow?(student)
    self.follow_students.include?(student)
  end

end

app/controllers/students/confirmations_controller.rb
# frozen_string_literal: true

class Students::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/students/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Students::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/students/passwords_controller.rb
# frozen_string_literal: true

class Students::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/students/registrations_controller.rb
# frozen_string_literal: true

class Students::RegistrationsController < Devise::RegistrationsController
  before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  def create
    super
    point = resource.build_watch_point
    point.save
  end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  def confirm_email

  end

  protected

  # If you have extra params to permit, append them to the sanitizer.
  def configure_sign_up_params
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name, :grade, :introduction, :image, :is_subscribe])
  end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  def after_sign_up_path_for(resource)
    new_student_educational_background_path(resource)
  end

  # The path used after sign up for inactive accounts.
  def after_inactive_sign_up_path_for(resource)
    confirm_email_path
  end
end

app/controllers/students/sessions_controller.rb
# frozen_string_literal: true

class Students::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end

  def after_sign_in_path_for(resource)
    root_path
  end

  def after_sign_out_path_for(resource)
    root_path
  end
end

app/controllers/students/unlocks_controller.rb
# frozen_string_literal: true

class Students::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/students_controller.rb
class StudentsController < ApplicationController
  before_action :set_student, only:[:show, :edit, :update, :destroy]

  def index
    @students = Student.all
  end

  def show
  end

  def edit
    unless current_student == @student
      flash[:danger] = "他人のプロフィールは変更できません"
      redirect_to student_path(current_student)
    end
  end

  def update
    if current_student == @student
      if @student.update(student_params)
        flash[:success] = "プロフィールを変更しました"
        redirect_to student_path(@student)
      else
        flash[:danger] = "プロフィールの変更に失敗しました。入力内容が正しいか確認してください"
        render :edit
      end
    else
      flash[:danger] = "他人のプロフィールは変更できません"
    end
  end

  def destroy
    if current_student == @student
      if @student.destroy
        flash[:success] = "退会しました。"
        redirect_to root_path
      else
        flash[:danger] = "退会に失敗しました。時間を置いて再度お試しください。解決しない場合は運営に問い合わせください。"
        redirect_to student_path(@student)
      end
    else
      flash[:danger] = "他人のアカウントを退会させることはできません"
    end
  end

  private
  def student_params
    params.require(:student).permit(:name, :grade, :email, :introduction, :is_subscribe, :image)
  end

  def set_student
    @student = Student.find(params[:id])
  end
end

app/helpers/students_helper.rb
module StudentsHelper
end

app/views/students/edit.html.erb
<div class="container-fluid">
  <div class="row">
    <h3 class="title">プロフィール変更</h3>
  </div>
  <%= form_for @student do |f|%>
    <div class="row">

      <div class="col-3">
        <h5 class="pa-20 center">プロフィール画像登録</h5>
        <div class="student_image-box center">
          <%= image_tag @student.info_image, id:"img-prev" %>
        </div>
        <div class="field pa-y-30 center">
          <%= f.file_field :image %>
        </div>
      </div>

      <div class="col-6">
        <div class="student_edit-main">
          <div class="field pa-y-30">
            <%= f.label :name, "ニックネーム" %>
            <%= f.text_field :name, autofocus: true, autocomplete: "name", class:"form-control", placeholder: "ニックネーム" %>
          </div>

          <div class="field pa-y-30">
            <%= f.label :grade, "学年" %><br>
            <% Student.grades_i18n.invert.each do |grade| %>
              <div class="radio_btn dis-ib pa-20">
                <%= f.radio_button :grade, grade[1] %>
                <%= f.label :grade, grade[0], value: grade[1] %>
              </div>
            <% end %>
          </div>

          <div class="field pa-y-30">
            <%= f.label :email, "メールアドレス" %><br />
            <%= f.email_field :email, autofocus: true, autocomplete: "email", class:"form-control" %>
          </div>

          <div class="field pa-y-30">
            <%= f.label :introduction, "自己紹介文" %>
            <%= f.text_area :introduction, autofocus: true, autocomplete: "introduction", class:"form-control", style:"height:300px" %>
          </div>

          <div class="actions right">
            <%= f.submit "変更する", class:"btn btn-primary" %>
          </div>  
        </div>
      </div>
  
      <div class="col-3 pa-30">
        <div class="student_edit-side wid-70 ma-a">
          <% if @student.educational_background.present? %>
            <%= link_to "学歴登録", edit_student_educational_background_path(@student, @student.educational_background), class:"btn btn-outline-info wid-100 ma-y-10" %>
          <% else %>
            <%= link_to "学歴登録", new_student_educational_background_path(@student), class:"btn btn-outline-info wid-100 ma-y-10" %>
          <% end %>
          <% if @student.aspire.present? %>
            <%= link_to "志望校登録", edit_student_aspire_path(@student, @student.aspire), class:"btn btn-outline-info wid-100 ma-y-10" %>
          <% else %>
            <%= link_to "志望校登録", new_student_aspire_path(@student), class:"btn btn-outline-info wid-100 ma-y-10" %>
          <% end %>
          <%= link_to "パスワード変更", edit_student_registration_path, class:"btn btn-outline-info wid-100 ma-y-10" %>
          <%= link_to "退会する", student_path(current_student), method: :delete, class:"btn btn-danger wid-100 ma-y-10" %>
        </div>
      </div>
    </div>
  <% end %>
</div>

app/views/students/index.html.erb
<div class="container">
  <div class="row">
    <div class="col-12">
      <div class="student_index-box">
        <h3 class="title">登録生徒一覧</h3>
        <table class="table table-hover center">
          <% if @students.any? %>
            <thead>
              <tr class="active">
                <th width="10%"></th>
                <th width="20%">ニックネーム</th>
                <th width="20%">学年</th>
                <th width="25%">投稿動画数</th>
                <th width="5%">国語</th>
                <th width="5%">数学</th>
                <th width="5%">社会</th>
                <th width="5%">理科</th>
                <th width="5%">英語</th>
              </tr>
            </thead>
            <% @students.each do |student| %>
              <tbody>
                <tr class="pointer" data-href="<%= student_path(student) %>">
                  <td class="right">
                    <%= image_tag student.thumnail_image, class:"circle", size: "50x50" %>
                  </td>
                  <td><%= student.name %></td>
                  <td><%= student.grade_i18n %></td>
                  <td></td>
                  <td>1</td>
                  <td>2</td>
                  <td>3</td>
                  <td>4</td>
                  <td>5</td>
                </tr>
              </tbody>
            <% end %>
          <% else %>
            <p class="ma-t-30 center">該当しませんでした</p>
          <% end %>
        </table>
      </div>
    </div>
  </div>
</div> 
    

app/views/students/show.html.erb
<div class="container">
  <div class="row">
    <% if @student == current_student %>
      <h3 class="title">マイページ</h3>
    <% else %>
      <h3 class="title">『<%= @student.name %>』さんの詳細ページ</h3>
    <% end %>
  </div>
  <div class="row">
    <div class="col-5">
      <div class="student_image-box center">
        <%= image_tag @student.info_image, id:"img-prev" %>
      </div>

      <div class="name center pa-t-30">
        <h3><%= @student.name %></h3>
      </div>

      <% if @student == current_student %>
        <div class="point-info center ma-y-10">
          <p class="gray">WatchPoint：　<%= @student.watch_point.point %>pt</p>
        </div>
      <% end %>

      <% if @student == current_student %>
        <div class="student_edit-link center pa-t-50">
          <%= link_to "プロフィール編集", edit_student_path(@student), class:"btn btn-info" %>
        </div>
      <% end %>
    </div>
    <div class="col-7">
      <div class="student_info-box">
        <div class="grade">
          <h4>学年：<%= @student.grade_i18n %></h4>
        </div>
        <div class="educational_background pa-t-30">
          <% if @student.aspire.present? %>
            <h4>志望校：<%= @student.aspire.school_name %>　<%= @student_aspire.faculty %></h4>
          <% else %>
            <h4>志望校：登録されていません</h4>
          <% end %>
        </div>
        <div class="educational_background pa-t-30">
          <h4>学歴</h4>
          <% if @student == current_student %>
            <%= render "educational_backgrounds/mypage" %>
          <% else %>
            <%= render "educational_backgrounds/otherpage" %>
          <% end %>
        </div>
      </div>
    </div>
  </div>
  <div class="row">
    <div class="col-12">
      <div class="introduction pa-30">
        <h4>自己紹介文</h4>
        <div class="detail pa-30" style="height:300px">
          <p><%= @student.introduction %></p>
        </div>
      </div>
    </div>
  </div>
</div>