config/routes.rb
Rails.application.routes.draw do
  get 'aspires/new'
  get 'aspires/edit'
  get 'educational_backgrounds/new'
  get 'educational_backgrounds/edit'
  root 'home#top'
  get 'home/about'
  devise_for :students, controllers:{
    sessions: "students/sessions",
    passwords: "students/passwords",
    registrations: "students/registrations"
  }
  resources :students, only:[:index, :show, :edit, :update, :destroy] do
    resources :educational_backgrounds, only:[:new, :create, :edit, :update]
    resources :aspires, only:[:new, :create, :edit, :update]
  end
  resources :follows, only:[:create, :destroy]
  resources :requests do
    get "videos/request_new"
    post "videos/request_create"
  end
  resources :videos do
    resources :comments, only:[:create, :destroy]
    resources :evaluations, only:[:create, :update, :destroy]
  end
  resources :communities do
    member do
      post "add"
      delete "out"
    end
    resources :tweets, only:[:new, :create, :destroy]
  end
  resources :tweets, only:[:show] do
    resources :reply_tweets, only:[:new, :create, :destroy]
    resources :tweet_evaluations, only:[:create, :destroy]
  end
  resources :comments, only:[:show] do
    resources :reply_comments, only:[:new, :create, :destroy]
    resources :comment_evaluations, only:[:create, :destroy]
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/aspire.rb
class Aspire < ApplicationRecord
  belongs_to :student
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :videos, dependent: :nullify
  has_many :requests, dependent: :nullify
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :student, optional: true
  belongs_to :video

  has_many :reply_comments, dependent: :destroy
  has_many :comment_evaluations, dependent: :destroy

  validates :detail, length:{maximum:400}
end

app/models/community.rb
class Community < ApplicationRecord
  # studentリレーション
  has_many :student_communities, dependent: :destroy
  has_many :students, through: :student_communities, source: "student"

  belongs_to :admin, class_name: "Student"

  has_many :tweets, dependent: :destroy

  validates :name, presence: true

  # 引数で渡された生徒がコミュニティに属しているか判別する
  def joined?(student)
    self.students.include?(student)
  end
end

app/models/evaluation.rb
class Evaluation < ApplicationRecord
  belongs_to :student, optional: true
  belongs_to :video

  enum high_low:{
    high: 0,
    low: 1
  }
  
end

app/models/follow.rb
class Follow < ApplicationRecord
  belongs_to :student
  belongs_to :follow, class_name: "Student"
end

app/models/reply_comment.rb
class ReplyComment < ApplicationRecord
  belongs_to :student, optional: true
  belongs_to :comment

  validates :detail, presence: true
end

app/models/reply_tweet.rb
class ReplyTweet < ApplicationRecord
  belongs_to :student
  belongs_to :tweet
end

app/models/request.rb
class Request < ApplicationRecord
  belongs_to :student
  belongs_to :category
  
  has_many :videos, dependent: :nullify

  enum academic_stage:{
    primary: 0, middle: 1, high: 2
  }

  # enum subject:{
  #   japanese: 0, math: 1, social: 2, sience: 3, english: 4
  # }

  # enum subject_content:{
  #   contemporary: 0, classic_literature: 1, chinese_classics: 2,
  #   arithmetic: 3, mathematics_1: 4, mathematics_a: 5, mathematics_2: 6, mathematics_b: 7, mathematics_3: 8, mathematics_c: 9,
  #   japanese_history: 10, world_history: 11, geography: 12,
  #   chemistry: 13, physical: 14, creature: 15
  # }

  validates :academic_stage, presence: true
  validates :title, presence: true
  validates :detail, presence: true, length:{maximum:500}

end

app/models/student.rb
class Student < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  enum grade:{
    p_1: 1, p_2: 2, p_3: 3, p_4: 4, p_5: 5, p_6: 6,
    m_1: 7, m_2: 8, m_3: 9, h_1: 10, h_2: 11, h_3: 12, other: 13
  }

  has_one :educational_background, dependent: :destroy
  has_one :watch_point, dependent: :destroy
  has_one :aspire, dependent: :destroy
  has_many :requests, dependent: :destroy
  has_many :videos, dependent: :nullify
  has_many :comments, dependent: :nullify
  has_many :evaluations, dependent: :nullify
  has_many :tweets, dependent: :nullify
  has_many :reply_tweets, dependent: :nullify
  has_many :tweet_evaluations, dependent: :nullify
  has_many :reply_comments, dependent: :nullify
  has_many :comment_evaluations, dependent: :nullify

  # watchリレーション
  has_many :watches, dependent: :nullify
  has_many :watched_videos, through: :watches, source: "video"

  # followリレーション
  has_many :follows, dependent: :destroy
  has_many :follow_students, through: :follows, source: "follow"
  has_many :followed, class_name: "Follow", foreign_key: "follow_id"
  has_many :followed_students, through: :followed, source: :student

  # communityリレーション
  has_many :student_communities, dependent: :destroy
  has_many :communities, through: :student_communities, source: "community"

  # adminになったコミュニティ
  has_many :communities, dependent: :nullify, foreign_key: "admin_id"

  mount_uploader :image, ImageUploader

  validates :name, presence: true
  validates :grade, presence: true

  def thumnail_image
    if self.image.blank?
      "no_image.png"
    else
      self.image.thumnail.to_s
    end
  end

  def info_image
    if self.image.blank?
      "no_image.png"
    else
      self.image.info.to_s
    end
  end

  def watched?(video)
    self.watches.find_by(video_id: video.id)
  end

  # 引数で渡された生徒をフォローする
  def follow(student)
    unless self == student
      self.follows.find_or_create_by(follow_id: student.id)
    end
  end

  # 引数で渡された生徒のフォローを解除する
  def unfollow(student)
    follow = self.follows.find_by(follow_id: student.id)
    follow.destroy if follow
  end

  # 引数で渡された生徒をフォローしているかを判別する
  def follow?(student)
    self.follow_students.include?(student)
  end

end

app/models/tweet.rb
class Tweet < ApplicationRecord
  belongs_to :student, optional: true
  belongs_to :community

  has_many :reply_tweets, dependent: :destroy
  has_many :tweet_evaluations, dependent: :destroy

  validates :detail, presence: true
end

app/models/video.rb
class Video < ApplicationRecord
  belongs_to :student, optional: true
  belongs_to :request, optional: true
  belongs_to :category

  has_many :watches, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :evaluations, dependent: :destroy

  enum academic_stage:{
    primary: 0, middle: 1, high: 2
  }

  mount_uploader :content, VideoUploader

  validates :academic_stage, presence: true
  validates :title, presence: true
  # validates :content, presence: true
  validates :detail, presence: true, length:{maximum:500}

end

app/models/watch.rb
class Watch < ApplicationRecord
  belongs_to :student
  belongs_to :video
end

app/models/watch_point.rb
class WatchPoint < ApplicationRecord
  belongs_to :student
end

app/controllers/tweets_controller.rb
class TweetsController < ApplicationController

  def show
    @tweet = Tweet.find(params[:id])
    @reply_tweets = @tweet.reply_tweets.all.order(created_at: :desc)
  end

  def new
    @tweet = Tweet.new
  end
  
  def create
    @community = Community.find(params[:community_id])
    @tweet = current_student.tweets.build(tweet_params)
    @tweet.community_id = @community.id
    if @tweet.save
      redirect_to community_path(@community)
    else
      render :new
    end
  end

  def destroy
    @community = Community.find(params[:community_id])
    @tweet = Tweet.find(params[:id])
    if @tweet.student == current_student
      if @tweet.destroy
        redirect_to community_path(@community)
      else
        redirect_to community_path(@community)
      end
    else
      flash[:danger] = "他の人の投稿を削除することはできません"
      redirect_to community_path(@community)
    end
  end

  private
  def tweet_params
    params.require(:tweet).permit(:student_id, :community_id, :detail)
  end
end

app/helpers/aspires_helper.rb
module AspiresHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/follows_helper.rb
module FollowsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/requests_helper.rb
module RequestsHelper
end

app/helpers/students_helper.rb
module StudentsHelper
end

app/helpers/tweets_helper.rb
module TweetsHelper
end

app/helpers/videos_helper.rb
module VideosHelper
end

app/views/tweets/_index.html.erb
<% if tweets.any? %>
  <% tweets.each do |tweet| %>  
    <div class="tweet-box ma-l-50 pa-y-20">
      <div class="tweet-info">
        <span class="tweet-student"><%= link_to "@#{tweet.student.name}", student_path(tweet.student) %></span>    
        <span class="tweet-date pa-l-20 gray"><%= tweet.created_at.strftime('%Y/%m/%d %H:%M:%S') %></span>
      </div>
      <div class="tweet-detail" id="tweet">
        <p class="pa-20"><%= tweet.detail %></p>
      </div>
      <div class="tweet-menu">
        <% if tweet.student == current_student %>
          <div class="menu-item right">
            <%= link_to "削除する", community_tweet_path(tweet.community_id, tweet.id), method: :delete, class: "tweet_destroy gray" %>
          </div>
        <% else %>
          <div id="tweet_evaluation_<%= tweet.id %>" class="dis-ib">
            <%= render "tweet_evaluations/evaluation_btn", tweet: tweet %>
          </div>
          <div class="response dis-ib pa-10">
            <%= link_to "返信", new_tweet_reply_tweet_path(tweet), class:"gray" %>
          </div>
        <% end %>
      </div>
      <% if tweet.reply_tweets.any? %>
        <h5>返信一覧</h5>
        <%= render partial: "tweets/reply_index", locals: {reply_tweets: tweet.reply_tweets.reverse, tweet: tweet} %>
        <% if tweet.reply_tweets.count > 10 %>
          <div class="index-link">
            <%= link_to "さらに返信を見る", tweet_path(tweet) %>
          </div>
        <% end %>
      <% end %>
    </div>
  <% end %>
<% else %>
  <p class="center">まだやりとりがありません</p>
<% end %>

app/views/tweets/_reply_index.html.erb
<% reply_tweets.first(10).each do |reply| %>  
  <div class="reply_tweet-box ma-l-30 ma-r-30 ma-y-10">
    <div class="reply_tweet-info">
      <span class="reply_tweet-student"><%= link_to "@#{reply.student.name}", student_path(reply.student) %></span>    
      <span class="reply_tweet-date pa-l-20 gray"><%= reply.created_at.strftime('%Y/%m/%d %H:%M:%S') %></span>
    </div>
    <div class="reply_tweet-detail" id="reply_tweet">
      <p class="pa-20"><%= reply.detail %></p>
    </div>
    <div class="reply_tweet-menu">
      <% if reply.student == current_student %>
        <div class="menu-item right">
          <%= link_to "削除する", tweet_reply_tweet_path(reply.tweet_id, reply.id), method: :delete, class: "tweet_reply_destroy gray" %>
        </div>
      <% end %>
    </div>
  </div>
<% end %>

app/views/tweets/new.html.erb
<div class="container">
  <div class="row">
    <div class="col-12">
      <h3 class="title">つぶやく</h3>

      <div class="tweet_form-box">
        <%= form_for @tweet, url: community_tweets_path(params[:community_id]) do |f|%>

          <div class="field pa-y-30">
            <% text = "今の気持ちや勉強している内容をみんなに共有してみよう！" %>
            <%= f.text_area :detail, autofocus: true, autocomplete: "detail", class:"form-control", placeholder: text, style:"height:300px" %>
          </div>

          <div class="actions right">
            <%= f.submit "つぶやく", class:"btn btn-primary" %>
          </div>
          
        <% end %>
      </div>
    </div>

  </div>
</div>

app/views/tweets/show.html.erb
<div class="container">
  <div class="row">
    <div class="col-12 pa-30">
      <div class="tweet_detail-box">
        <div class="student">
          <div class="thumnail-image dis-ib">
            <%= image_tag @tweet.student.thumnail_image, size:"50x50", class:"circle" %>
          </div>
          <div class="name-box dis-ib pa-10">
            <%= link_to @tweet.student.name, student_path(@tweet.student) %>
          </div>
        </div>
        <div class="info right">
          <h6 class="gray"><%= @tweet.created_at.strftime("%Y/%m/%d %H:%M:%S") %></h6>
        </div>
      </div>
      <div class="detail pa-30">
        <p><%= @tweet.detail %></p>
      </div>
      <div class="reply-link right">
        <%= link_to "返信する", new_tweet_reply_tweet_path(@tweet), class:"btn btn-primary" %>
      </div>
    </div>
  </div>
  <hr>
  <div class="low">
    <div class="col-12">
      <h5 class="title">返信一覧</h5>
      <div class="reply_tweet_index-box pa-x-50">
        <%= render "reply_tweets/index", reply_tweets: @reply_tweets %>
      </div>
    </div>
  </div>
</div>