config/routes.rb
Rails.application.routes.draw do
  get 'aspires/new'
  get 'aspires/edit'
  get 'educational_backgrounds/new'
  get 'educational_backgrounds/edit'
  root 'home#top'
  get 'home/about'
  devise_for :students, controllers:{
    sessions: "students/sessions",
    passwords: "students/passwords",
    registrations: "students/registrations"
  }
  resources :students, only:[:index, :show, :edit, :update, :destroy] do
    resources :educational_backgrounds, only:[:new, :create, :edit, :update]
    resources :aspires, only:[:new, :create, :edit, :update]
  end
  resources :follows, only:[:create, :destroy]
  resources :requests do
    get "videos/request_new"
    post "videos/request_create"
  end
  resources :videos do
    resources :comments, only:[:create, :destroy]
    resources :evaluations, only:[:create, :update, :destroy]
  end
  resources :communities do
    member do
      post "add"
      delete "out"
    end
    resources :tweets, only:[:new, :create, :destroy]
  end
  resources :tweets, only:[:show] do
    resources :reply_tweets, only:[:new, :create, :destroy]
    resources :tweet_evaluations, only:[:create, :destroy]
  end
  resources :comments, only:[:show] do
    resources :reply_comments, only:[:new, :create, :destroy]
    resources :comment_evaluations, only:[:create, :destroy]
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/request.rb
class Request < ApplicationRecord
  belongs_to :student
  belongs_to :category
  
  has_many :videos, dependent: :nullify

  enum academic_stage:{
    primary: 0, middle: 1, high: 2
  }

  # enum subject:{
  #   japanese: 0, math: 1, social: 2, sience: 3, english: 4
  # }

  # enum subject_content:{
  #   contemporary: 0, classic_literature: 1, chinese_classics: 2,
  #   arithmetic: 3, mathematics_1: 4, mathematics_a: 5, mathematics_2: 6, mathematics_b: 7, mathematics_3: 8, mathematics_c: 9,
  #   japanese_history: 10, world_history: 11, geography: 12,
  #   chemistry: 13, physical: 14, creature: 15
  # }

  validates :academic_stage, presence: true
  validates :title, presence: true
  validates :detail, presence: true, length:{maximum:500}

end

app/controllers/requests_controller.rb
class RequestsController < ApplicationController
  before_action :set_request, only:[:show, :edit, :update, :destroy]

  def index
    @requests = Request.all
  end

  def show
  end

  def new
    @request = Request.new
  end

  def create
    @request = current_student.requests.build(request_params)
    if @request.save
      flash[:success] = "リクエストしました"
      redirect_to requests_path
    else
      flash.now[:danger] = "リクエストに失敗しました"
      render :new
    end
  end

  def edit
    unless @request.student == current_student
      flash[:danger] = "他人のリクエストを変更することはできません"
      redirect_to student_path(current_student)
    end
  end

  def update
    if @request.student == current_student
      if @request.update(request_params)
        flash[:success] = "リクエストを編集しました"
        redirect_to requests_path
      else
        flash.now[:danger] = "リクエストの編集に失敗しました"
        render :edit
      end
    else
      flash[:danger] = "他人のリクエストを変更することはできません"
      redirect_to student_path(current_student)
    end
  end

  def destroy
    if @request.student == current_student
      if @request.destroy
        flash[:success] = "リクエストを削除しました"
        redirect_to requests_path
      else
        flash[:danger] = "リクエストを削除できませんでした"
        redirect_to requests_path
      end
    else
      flash[:danger] = "他人のリクエストを削除することはできません"
      redirect_to student_path(current_student)
    end
  end

  private
  def request_params
    params.require(:request).permit(:student_id, :category_id, :academic_stage, :title, :detail, :is_active)
  end

  def set_request
    @request = Request.find(params[:id])
  end
end

app/helpers/requests_helper.rb
module RequestsHelper
end

app/views/requests/_form.html.erb
<%= form_for @request do |f| %>

  <div class="field pa-y-30">
    <%= f.label :academic_stage, "対象レベル" %><br>
    <% Request.academic_stages_i18n.invert.each do |academic_stage| %>
      <div class="radio_btn dis-ib pa-10">
        <%= f.radio_button :academic_stage, academic_stage[1] %>
        <%= f.label :academic_stage, academic_stage[0], value: academic_stage[1] %>
      </div>
    <% end %>
  </div>

  <div class="field pa-y-30">
    <%= f.label :subject, "対象教科" %><br>
    <% Request.subjects_i18n.invert.each do |subject| %>
      <div class="radio_btn dis-ib pa-10">
        <%= f.radio_button :subject, subject[1] %>
        <%= f.label :subject, subject[0], value: subject[1] %>
      </div>
    <% end %>
  </div>

  <div class="field pa-y-30">
    <%= f.label :subject_content, "対象教科" %><br>
    <% Request.subject_contents_i18n.invert.each do |subject_content| %>
      <div class="radio_btn dis-ib pa-10">
        <%= f.radio_button :subject_content, subject_content[1] %>
        <%= f.label :subject_content, subject_content[0], value: subject_content[1] %>
      </div>
    <% end %>
  </div>

  <div class="field pa-y-30">
    <%= f.label :title, "タイトル" %>
    <%= f.text_field :title, autofocus: true, autocomplete: "title", class:"form-control", placeholder: "【青チャート】p.5 大問1　微分について" %>
  </div>

  <div class="field pa-y-30">
    <%= f.label :detail, "質問詳細" %>
    <%= f.text_area :detail, autofocus: true, autocomplete: "detail", class:"form-control", style:"height:300px" %>
  </div>

  <div class="actions right">
    <%= f.submit btn, class:"btn btn-primary" %>
  </div>

<% end %>

app/views/requests/edit.html.erb
<div class="container">
  <div class="row">
    <div class="col-12">
      <h3 class="title">リクエスト編集</h3>
      <div class="request_form-box">
        <%= render "requests/form", btn: "編集する" %>
      </div>
    </div>
  </div>
</div>

app/views/requests/index.html.erb
<div class="container">
  <div class="row">
    <div class="col-12">
      <h3 class="title">リクエスト一覧</h3>
      <div class="request_index-box">
        <% if @requests.any? %>
          <% @requests.each do |request| %>
            <div class="request_index-item pa-20 box">
              <div class="sub-title">
                <h4><%= link_to request.title, request_path(request) %></h4>
              </div>
              <div class="request_info">
                <div class="level">
                  <p>必要レベル：<%= request.academic_stage_i18n %></p>
                </div>
                <div class="subject">
                  <p>教科：<%= request.subject_i18n %><span class="pa-l-20">分野：<%= request.subject_content_i18n %></span></p>
                </div>
                <div class="review">
                  評価(○件)：
                </div>
                <div class="post">
                  <span>投稿者：<%= request.student.name %></span><br>
                  <span>投稿日時：<%= request.created_at.strftime("%Y/%m/%d %H:%M") %></span>
                </div>
              </div>
            </div>
          <% end %>
        <% else %>
          <p class="center">現在、リクエストはありません</p>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/requests/new.html.erb
<div class="container">
  <div class="row">
    <div class="col-12">
      <h3 class="title">リクエスト作成</h3>
      <div class="request_form-box">
        <%= render "requests/form", btn: "リクエストする" %>
      </div>
    </div>
  </div>
</div>

app/views/requests/show.html.erb
<div class="container">
  <div class="row">
    <div class="col-12">
      <div class="request_detail-box">
        <h3 class="title"><%= @request.title %></h3>
        <div class="post-date pa-20 right">
          <span>投稿日時：<%= @request.created_at.strftime("%Y/%m/%d %H:%M") %></span>
        </div>
        <hr>
        <div class="review">
          評価　〇〇件：
        </div>
        <h5 class="title">リクエスト詳細</h5>
        <div class="level">
          <p>必要レベル：<%= @request.academic_stage_i18n %></p>
        </div>
        <div class="subject">
          <p>教科：<%= @request.subject_i18n %><span class="pa-l-20">分野：<%= @request.subject_content_i18n %></span></p>
        </div>
        <div class="introduction">
          <p><%= simple_format(@request.detail) %></p>
        </div>
        <% if @request.student == current_student %>
          <div class="link-box pa-10 ma-t-10 right">
            <span class="ma-r-20"><%= link_to "内容を編集する", edit_request_path(@request), class: "btn btn-primary" %></span>
            <span><%= link_to "削除", request_path(@request),method: :delete, class: "btn btn-danger" %></span>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>